import type { OutfitAdvice } from '@/lib/outfit'

const OPENAI_MODEL = 'gpt-4o-mini'
const OPENAI_MAX_TOKENS = 90
const OPENAI_TEMPERATURE = 0.3
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions'

export async function getAIOutfitAdvice(prompt: string): Promise<OutfitAdvice> {
  const OPENAI_API_KEY = process.env.OPENAI_API_KEY
  if (!OPENAI_API_KEY) throw new Error('NO_KEY')

  const body = {
    model: OPENAI_MODEL,
    messages: [{ role: 'user', content: prompt }],
    max_tokens: OPENAI_MAX_TOKENS,
    temperature: OPENAI_TEMPERATURE,
  }

  const response = await fetch(OPENAI_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify(body),
  })

  if (!response.ok) {
    throw new Error(`OPENAI_${response.status}`)
  }

  const data = (await response.json()) as {
    choices?: { message?: { content?: string } }[]
  }

  const content = data.choices?.[0]?.message?.content
  if (!content) throw new Error('NO_CONTENT')

  const text =
    content
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
      .join(' ')
      .trim() || ''

  if (!text) throw new Error('EMPTY_CONTENT')

  return {
    headline: 'What to wear today (AI)',
    text,
    note: 'Generated by OpenAI gpt-4o-mini; falls back to rule-based if unavailable.',
  }
}
